<?php
includeView('header', 'Home');
?>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css">
<body class="mb-5">
    <div class="container mt-5">
        <div class="container mt-5">
            <h3 class="text-center">Sistema de Tickets V 2.0</h3>
            <div class="row d-flex justify-content-center">
                <div class="card mt-5" style="width: 30rem;">
                    <div class="card-body">
                        <form method="POST" action="/login">
                            <div class="mb-3">
                                <label for="exampleInputEmail1" class="form-label">Email</label>
                                <input type="email" class="form-control" name="email" required>
                            </div>
                            <div class="mb-3">
                                <label for="exampleInputPassword1" class="form-label">Password</label>
                                <input type="password" class="form-control" name="password" required>
                            </div>
                            <span class="text-danger"><small><b><?=getFlashMessage()?></b></small></span>
                            <!-- <div class="mb-3 form-check">
                                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                <label class="form-check-label" for="exampleCheck1">Check me out</label>
                            </div> -->
                            <div class="d-flex justify-content-center">
                                <button type="submit" class="btn btn-primary">Ingresar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<?php
includeView('footer');
?>