<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?=$code?></title>
    <link rel="stylesheet" href="/css/main.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>
</head>

<body>

    <nav class="navbar navbar-light bg-danger">
        <div class="container">
            <a class="navbar-brand" href="#">
                <img src="/icons/fantasma.svg" alt="" width="50" height="50">
            </a>
            <h3 class="text-light">¡¡¡Ha ocurrido un error!!!</h3>
        </div>
    </nav>
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">
               <strong>Throw Class</strong>: <?=$exception::class?>
               <hr>
               <strong>Message:</strong> <?=$exception->getMessage()?>
               <hr>
               <strong>File:</strong> <?=$exception->getFile()?>
               <hr>
               <strong>Line:</strong> <?=$exception->getLine()?>
            </div>
        </div>
        <?php echo '<pre>';
         $lines = file($exception->getFile(), FILE_IGNORE_NEW_LINES );
         foreach ($lines as $line=>$content) {
             if($line){
                 if(str_starts_with($content,'/') || str_starts_with($content,'#')){
                    echo ($line+1).' ',"<span class='text-success' style='font-style: italic !important;'>",$content,"</span>";
                 }
                else if($line == ($exception->getLine()-1)){
                    echo "<div class='text-danger'>".($line+1).' ',$content,"</div>";
             }else{
                echo ($line+1).' ',$content;
                }
             }
             echo '<br>';
             
         }
        echo '</pre>';?>
        
    </div>
</body>

</html>